### ISSUE TITLE
Support updating the root domain

### ISSUE THREAD

**Issue by stellarpower** [alcroito/digitalocean-dyndns#3]
I'd like to use this because I have an existing DDNS service and Digital Ocean suports DNS challenges for certbot, but, doesn't allow flattened CNAME entries. Therefore, I have a need to update the root domain address, and not just a subdomain.

I've tried an empty environment variable, but it then outputs with a trailing dot for `.mywebsite.com`, and I can see this in the [code](https://github.com/alcroito/digitalocean-dyndns/blob/ae7ba8336e530ea6cca6176419442c4d3cd26d25/src/domain_updater.rs#L164) where an FQDN is being generated. The JSON coming back from the API has `@` in it, so how you would want to implement proper scanning of the config is up to you but the API side should be pretty easy.

Thanks :)

**Comment by alcroito** [comment]
To clarify, are you asking to update the A record of the root domain via the Digital Ocean API?

**Comment by stellarpower** [comment]
Yes, exactly that.


28 Feb 2021 14:35:51 alcroito <notifications@github.com>:

**Comment by stellarpower** [comment]
Thanks!!! I will pull the new docker image as soon as I can :D
